llms:
  google/gemma:
    - google/gemma-3-270m-it
    - google/gemma-3-4b-it
    - google/gemma-3-12b-it
    - google/gemma-3-27b-it
  HuggingFaceTB/SmolLM:
    - HuggingFaceTB/SmolLM-135M-Instruct
    - HuggingFaceTB/SmolLM-360M-Instruct
    - HuggingFaceTB/SmolLM-1.7B-Instruct
  Qwen:
    - Qwen/Qwen3-4B-Instruct-2507
    - Qwen/Qwen2.5-7B-Instruct
    - Qwen/Qwen2.5-32B-Instruct
  meta-llama:
    - meta-llama/Meta-Llama-3-8B-Instruct
    - meta-llama/Llama-3.1-8B-Instruct
  mistralai:
    - mistralai/Mistral-Small-Instruct-2409
    - mistralai/Mistral-Small-24B-Instruct-2501
  deepseek-ai:
    - deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  microsoft:
    - microsoft/Phi-3-medium-4k-instruct

XAI_LEVEL_NAMES:
  - "LEVEL_0": 
    - "Completion"
    - "Conversation"
    - "Regression"
    - "Binary Classification" 
    - "Multiclass Classification"
    - "Jailbreak"
  - "LEVEL_1":
    - "Response Attribution"
    - "Positive & Negative Attribution"
    - "Adversarial Text Generation"
  - "LEVEL_2":
    - "Layer Direction Similarity Analysis"
    - "Brain Concept Visualization"
    - "Positive and Negative Response Preference"
    - "Residual Concept Detection"

TREATMENTS:
  - "Simple Steering"


ANALYZER:
  - "Layer Residual PCA"


DATASETS:
  jailbreak:
    - walledai/XSTest
    - walledai/JailbreakBench
    - PKU-Alignment/BeaverTails
    - Anthropic/hh-rlhf
  factual:
    - m-a-p/CounterFact
    - truthful_qa
    - felixzhao/NQ-Swap
  reasoning:
    - google/BIG-bench
    - TIGER-Lab/StrategyQA